const resources = {
  label_filter_reset: "Reset",
  label_filter_apply: "Apply",
  label_book_now: "Book Now",
  label_confirm: "Confirm",
  label_cancel: "Cancel",
  label_stay_duration: "Stay Duration",
  label_guests: "Guest/s",
  label_group_size: "Group Size",
  label_accommodation_type: "Accommodation Type",
  label_price_per_night: "Price Per Night",
  label_filter: "Filters",
  label_per_day: "Per Day",
  label_loading: "Loading...",
  label_phone_number: "Phone Number",
  label_email: "Email",
  label_last_name: "Last Name",
  label_first_name: "First Name",
  label_properties_for_rent: "properties for rent in the greater Amsterdam region",
  label_calculation: "Calculation: €",
  label_total_cost: "Total Cost (incl. Taxes): €",
  label_back_to_dashboard: "Back To Dashboard",
  nav_uni_header: "Amsterdam Metropolitan University",
  nav_home: "Home",
  nav_rooms: "Rooms",
  nav_contact: "Contact us",
  message_data_permission: "I give permission to save the data I have entered here and use this data to contact me. More information in our privacy statement.",
  message_booking_loading: "is being booked! Please wait...",
  message_booking_confirmed: "Booking Confirmed",
  message_enjoy_your_stay: "Enjoy your stay!",
  error_stay_duration: "Please select your stay duration before making a booking!",
  error_first_name_required: "First Name is required",
  error_invalid_first_name: "First Name should only contain alphabetic characters",
  error_last_name_required: "Last Name is required",
  error_invalid_last_name: "Last Name should only contain alphabetic characters",
  error_email_required: "Email is required",
  error_invalid_email: "Email should be a valid email address",
  error_phone_number_required: "Phone Number is required",
  error_invalid_phone_number: "Phone Number should be a valid phone number",
  error_data_permission_required: "Data permission is required",
  error_properties_for_rent: "No properties found matching your filters. Try adjusting or removing one of your filters.",
};
export default resources;
