import room from "./assets/apart.jpeg";

export const cardsData = [
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Bicycle storage", "Free Wi-Fi", "Pool"],
    type: "villa",
    from: "2021-10-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["1 guests", "Heating and/or air conditioning", "Free Wi-Fi"],
    type: "flat",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 2",
    size: 20,
    price: 2000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["4 guests", "Pool", "Free Wi-Fi", "Gym"],
    type: "house",
    from: "2021-05-01",
    to: "2021-11-05",
    location: "location 3",
    size: 30,
    price: 3000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "apartment",
    from: "2021-02-01",
    to: "2021-12-05",
    location: "location 4",
    size: 40,
    price: 4000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["1 guests", "Pool", "Free Wi-Fi", "Gym"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["3 guests", "Heating and/or air conditioning", "Free Wi-Fi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["4 guests", "Bicycle storage", "Free Wi-Fi", "Pool", "Gym"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Free Parking", "Wifi", "Gym"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["2 guests", "Laundry facilities", "Free Wi-Fi", "Free Parking"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  {
    title: "Full Furnished Smart Studio Apartments",
    description:
      "This room is fully upholstered and furnished. You only need to bring your personal items. Even bedding has been thought of.\n\nYou share the bathroom and toilets with your roommates. You cook in the communal kitchen, there is a (shared) refrigerator and a cooker. There is a box with kitchen utensils waiting for you or the kitchen is equipped upon arrival.",
    image: room,
    alt: "product image",
    features: ["1 guests", "Heating and/or air conditioning", "Free Wi-Fi"],
    type: "villa",
    from: "2021-05-01",
    to: "2021-10-05",
    location: "location 1",
    size: 10,
    price: 1000,
  },
  // Add more card data objects as needed
];
